sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t bcrd/zcash:latest zcash/.
  - docker build -t bcrd/zcash-tor:latest zcash-tor/.
  - docker build -t bcrd/zcash-testnet:latest zcash-testnet/.


script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bcrd/zcash:latest
  - docker push bcrd/zcash-tor:latest
  - docker push bcrd/zcash-testnet:latest
